// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutritionTrackingApp.Infrastructure;

#nullable disable

namespace NutritionTrackingApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NutritionTrackingApp.Core.Entities.FoodEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Calories")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Carbs")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Fat")
                        .HasColumnType("numeric");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Protein")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Sugar")
                        .HasColumnType("numeric");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("UserId");

                    b.ToTable("food_entries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 150m,
                            Calories = 50m,
                            Carbs = 200m,
                            CreatedAt = new DateTime(2025, 11, 27, 21, 22, 24, 502, DateTimeKind.Utc).AddTicks(632),
                            Fat = 5m,
                            IngredientId = 1,
                            Protein = 10m,
                            Sugar = 120m,
                            Unit = "g",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 120m,
                            Calories = 100m,
                            Carbs = 250m,
                            CreatedAt = new DateTime(2025, 11, 27, 21, 22, 24, 502, DateTimeKind.Utc).AddTicks(637),
                            Fat = 10m,
                            IngredientId = 2,
                            Protein = 15m,
                            Sugar = 40m,
                            Unit = "g",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 100m,
                            Calories = 120m,
                            Carbs = 200m,
                            CreatedAt = new DateTime(2025, 11, 27, 21, 22, 24, 502, DateTimeKind.Utc).AddTicks(639),
                            Fat = 60m,
                            IngredientId = 3,
                            Protein = 90m,
                            Sugar = 5m,
                            Unit = "g",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("NutritionTrackingApp.Core.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpoonacularId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpoonacularId")
                        .IsUnique();

                    b.ToTable("ingredients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "apple",
                            SpoonacularId = 9000
                        },
                        new
                        {
                            Id = 2,
                            Name = "bread",
                            SpoonacularId = 9001
                        },
                        new
                        {
                            Id = 3,
                            Name = "beef",
                            SpoonacularId = 9002
                        });
                });

            modelBuilder.Entity("NutritionTrackingApp.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 27, 21, 22, 24, 502, DateTimeKind.Utc).AddTicks(619),
                            PasswordHash = "$2a$11$b8gfSsf3lTecGBuZoccxbOzj8sl95RUiIm9pPmfvFqNKkfhthC56.",
                            Username = "testuser"
                        });
                });

            modelBuilder.Entity("NutritionTrackingApp.Core.Entities.FoodEntry", b =>
                {
                    b.HasOne("NutritionTrackingApp.Core.Entities.Ingredient", "Ingredient")
                        .WithMany("FoodEntries")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NutritionTrackingApp.Core.Entities.User", "User")
                        .WithMany("FoodEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutritionTrackingApp.Core.Entities.Ingredient", b =>
                {
                    b.Navigation("FoodEntries");
                });

            modelBuilder.Entity("NutritionTrackingApp.Core.Entities.User", b =>
                {
                    b.Navigation("FoodEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
